version: '3.8'
services:
  app:
    build: .
    container_name: product-search-api
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: products_db
    ports:
      - '3201:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '3202:6379'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '3203:9200'

volumes:
  mysql-data: