version: '3.8'
services:
  app:
    build: .
    container_name: product-search-api
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: products_db
    ports:
      - '3201:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '3202:6379'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - '3203:9200'
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kib01
    environment:
      XPACK_APM_SERVICEMAPENABLED: "true"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: aaaaaaaa-c4d3-4a0a-8290-2abcb83ab3aa

    ports:
      - 5601:5601

volumes:
  mysql-data: